[project]
name = "rag-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "csagnik1302", email = "sagnikc2003@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.14.0",
    "bitsandbytes>=0.50.2",
    "datasets>=5.0.1",
    "fastembed>=0.8.0",
    "fpdf2>=2.8.8",
    "google>=3.0.0",
    "google-genai>=2.23.0",
    "langchain>=1.4.0",
    "langchain-community>=0.4.2",
    "langchain-huggingface>=1.2.2",
    "langgraph>=1.2.11",
    "matplotlib>=3.11.1",
    "pymupdf>=1.28.2",
    "qdrant-client[fastembed]>=1.14.1",
    "scikit-learn>=1.9.0",
    "sentence-transformers>=6.0.1",
    "streamlit>=1.63.0",
    "tqdm>=4.70.0",
    "wikipedia-api>=0.16.0",
]

[project.scripts]
rag-project = "rag_project:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
